# Copyright (C) 2026 Прокофьев Даниил <d@dvprokofiev.ru>
# Лицензировано под GNU Affero General Public License v3.0
# Часть проекта генератора рассадок
services:
  engine:
    image: ghcr.io/dvprokofiev/seating-generator-engine:latest
    container_name: seating-generator-engine
    ports: 
      - "8091:5000"

  frontend:
    image: ghcr.io/dvprokofiev/seating-generator-frontend:latest
    container_name: seating-generator-frontend
    ports:
      - "8092:80"
    depends_on: 
      - engine
